-- MySQL Script generated by MySQL Workbench
-- Tue Nov 13 11:44:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema d2decoy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d2decoy
-- -----------------------------------------------------
CREATE SCHEMA `d2decoy` ;
USE `d2decoy` ;
-- -----------------------------------------------------
-- Table `d2decoy`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Customer` (
  `customerID` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` INT(10) NULL,
  `streetLine1` VARCHAR(45) NULL,
  `streetLine2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` INT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `d2decoy`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Locations` (
  `locationID` INT NOT NULL,
  `locationName` VARCHAR(45) NULL,
  `streetLine1` VARCHAR(45) NULL,
  `streetLine2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` INT NULL,
  PRIMARY KEY (`locationID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `d2decoy`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Products` (
  `productID` INT NOT NULL,
  `productName` VARCHAR(45) NULL,
  `productType` VARCHAR(45) NULL,
  `price` DECIMAL(6,2) NULL,
  `productDesc` LONGTEXT NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d2decoy`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Inventory` (
  `Locations_locationID` INT NOT NULL,
  `Products_productID` INT NOT NULL,
  `numStock` INT NULL,
  PRIMARY KEY (`Locations_locationID`, `Products_productID`),
  INDEX `fk_Locations_has_Products_Products1_idx` (`Products_productID` ASC) VISIBLE,
  INDEX `fk_Locations_has_Products_Locations_idx` (`Locations_locationID` ASC) VISIBLE,
  CONSTRAINT `fk_Locations_has_Products_Locations`
    FOREIGN KEY (`Locations_locationID`)
    REFERENCES `d2decoyhhc`.`Locations` (`locationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locations_has_Products_Products1`
    FOREIGN KEY (`Products_productID`)
    REFERENCES `d2decoyhhc`.`Products` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d2decoy`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Cart` (
  `cartID` INT NOT NULL,
  `Customers_customerID` INT NOT NULL,
  PRIMARY KEY (`cartID`),
  INDEX `fk_Cart_Customers1_idx` (`Customers_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_Customers1`
    FOREIGN KEY (`Customers_customerID`)
    REFERENCES `d2decoyhhc`.`Customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d2decoy`.`CartItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`CartItems` (
  `Cart_cartID` INT NOT NULL,
  `Products_productID` INT NOT NULL,
  `quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`Cart_cartID`, `Products_productID`),
  INDEX `fk_Cart_has_Products_Products1_idx` (`Products_productID` ASC) VISIBLE,
  INDEX `fk_Cart_has_Products_Cart1_idx` (`Cart_cartID` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_has_Products_Cart1`
    FOREIGN KEY (`Cart_cartID`)
    REFERENCES `d2decoyhhc`.`Cart` (`cartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_has_Products_Products1`
    FOREIGN KEY (`Products_productID`)
    REFERENCES `d2decoyhhc`.`Products` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
