-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 12:39:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema d2decoy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d2decoy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `d2decoy` ;
USE `d2decoy` ;

-- -----------------------------------------------------
-- Table `d2decoy`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Customer` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` INT(10) NULL DEFAULT NULL,
  `streetLine1` VARCHAR(45) NULL DEFAULT NULL,
  `streetLine2` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` INT NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d2decoy`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Location` (
  `locationID` INT NOT NULL,
  `locationName` VARCHAR(45) NULL DEFAULT NULL,
  `streetLine1` VARCHAR(45) NULL DEFAULT NULL,
  `streetLine2` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` INT NULL DEFAULT NULL,
  PRIMARY KEY (`locationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d2decoy`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Products` (
  `productID` INT NOT NULL,
  `productName` VARCHAR(45) NULL DEFAULT NULL,
  `productType` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) NULL DEFAULT NULL,
  `productDesc` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d2decoy`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Inventory` (
  `numStock` INT NULL DEFAULT NULL,
  `Products_productID` INT NOT NULL,
  `Location_locationID` INT NOT NULL,
  PRIMARY KEY (`Products_productID`, `Location_locationID`),
  INDEX `fk_Inventory_Location1_idx` (`Location_locationID` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Products1`
    FOREIGN KEY (`Products_productID`)
    REFERENCES `d2decoy`.`Products` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventory_Location1`
    FOREIGN KEY (`Location_locationID`)
    REFERENCES `d2decoy`.`Location` (`locationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d2decoy`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`Cart` (
  `cartID` INT NOT NULL,
  `Customer_customerID` INT NOT NULL,
  PRIMARY KEY (`cartID`),
  INDEX `fk_Cart_Customer_idx` (`Customer_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_Customer`
    FOREIGN KEY (`Customer_customerID`)
    REFERENCES `d2decoy`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d2decoy`.`CartItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d2decoy`.`CartItems` (
  `quantity` VARCHAR(45) NULL DEFAULT NULL,
  `Cart_cartID` INT NOT NULL,
  `Products_productID` INT NOT NULL,
  PRIMARY KEY (`Cart_cartID`, `Products_productID`),
  INDEX `fk_CartItems_Products1_idx` (`Products_productID` ASC) VISIBLE,
  CONSTRAINT `fk_CartItems_Cart1`
    FOREIGN KEY (`Cart_cartID`)
    REFERENCES `d2decoy`.`Cart` (`cartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartItems_Products1`
    FOREIGN KEY (`Products_productID`)
    REFERENCES `d2decoy`.`Products` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
